<div class = "container sub-banner" >

<div class = "Block 1" style="float: left">

  <a href="<?=$block->getData('url1')?>">  <img src="<?=$block->getData('hinh1')?>" style="width: 600px;height: 300px"/></a>

</div>

<div class = "Block 1" style ="float:left">
  <a href = "<?=$block->getData('url2')?>">  <img src="<?=$block->getData('hinh1')?>" style="width: 600px;height: 300px"/> </a>

</div>

</div>

<style>
    .Block
    {
        padding: 5px;
    }

    .container.sub-banner {
        display: flex;
        justify-content: space-around;
        j
    }
</style>



