<div class = "container">

<div class = "Block 1" style="float: left">

   <a href = "<?=$block->getData('url1')?>" > <img src="<?=$block->getData('hinh2')?>" style="width: 400px;height: 300px"/> </a>

</div>
<div class = "Block 1" style = "float: left">

<a href = "<?=$block->getData('url2')?>" >  <img src="<?=$block->getData('hinh3')?>" style="width: 400px;height: 300px"/> </a>
</div>

<div class = "Block 1" style ="float:left">
<a href = "<?=$block->getData('url3')?>" >   <img src="<?=$block->getData('hinh1')?>" style="width: 400px;height: 300px"/></a>

</div>

</div>

<style>
    .Block
    {
        padding: 5px;
    }
</style>




