<div class = "sub_banner_3">

        <div class = "Block 1" style="float: left">

            <img src="<?=$block->getData('hinh2')?>" style="width: 400px;height: 300px"/>

        </div>
        <div class = "Block 1" style = "float: left">

            <img src="<?=$block->getData('hinh3')?>" style="width: 400px;height: 300px"/>
        </div>

        <div class = "Block 1" style ="float:left">
            <img src="<?=$block->getData('hinh1')?>" style="width: 400px;height: 300px"/>

        </div>

</div>






