<?php
$dataconfig =$block->getConfigs();
$categoryId = 5;
$numberofproduct = $dataconfig['maxproductslider'];
$getProudctcollection = $block->getCategoryProduct($categoryId,$numberofproduct);
?>

<style>
    .product-item{
        float: left;
    }

    .block-title strong {
        font-weight: 600 !important;
    }



    .product-item-info {
        position: relative;

    }
    .line {
        width: 100%;
        height: 1px;
        background: #C7C7C7;
    }

    .product-item-info .note {
        position: absolute;
        top: 1%;
        left: 15%;
        border: 1px solid #0c0c0c;
        box-shadow: 2px 2px #000;
        padding: 2px 5px;
        background: red;
        color: #fff;
        text-transform: uppercase;
        font-weight: 800;
        font-size: 1rem;
    }

    .price {
        display: block;
        text-align: center;
    }
    .block {
        height: auto;
        width: 100%;
    }
    .products {
        width: 100%;
        display: inline-block;
    }

    .landing-item {
        margin-left: 20px;
    }
    .landing-item a img {
        width: 100%;
    }





    </style>


<div class="block" id="recently_viewed_container">
    <div class="content">
        <ol class="products list items">

            <?php foreach ($getProudctcollection as $product): ?>
                <?php

                $name = $product->getName();
                $img = $product->getImage();
                $image = 'new_products_content_widget_list';


                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $_product = $objectManager->get('Magento\Catalog\Model\Product')->load($product->getProductId());
                $imageHelper = $objectManager->get('\Magento\Catalog\Helper\Image');
                $image_url = $imageHelper->init($_product, 'product_page_image_small')->setImageFile($product->getImage())->resize(340, 400)->getUrl();
                $priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
                $price = $priceHelper->currency($product->getFinalPrice(), true, false);
                ?>

                <li class="product-item landing-item">
                    <div class="product-item-info">

                        <a href="<?php echo $product->getProductUrl(); ?>">
                            <img src="<?= $image_url ?>"/>
                        </a>

                        <div class="product-item-details">
                            <strong class="product-item-name">
                                <a title="<?= $name ?>"
                                   href="<?php echo $product->getProductUrl(); ?>"
                                   class="product-item-link">
                                    <?= $name ?> </a>
                            </strong>
                            <div class="line"></div>
                            <div class="price-box price-final_price" data-role="priceBox" data-product-id="1996"
                                 data-price-box="product-id-1996">
                                    <span class="normal-price">
                                        <span class="price-container price-final_price tax weee">
                                            <span id="old-price-1996-widget-new-grid" data-price-amount="42"
                                                  data-price-type="finalPrice"
                                                  class="price-wrapper "><span
                                                        class="price"><?= $price ?></span></span>
                                            </span>
                                    </span>
                            </div>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <script>
        require([
            'jquery',
            'slick'
        ], function ($) {
            $(document).ready(function () {
                $(".items").slick({
                    arrows: true,
                    infinite: false,
                    speed: 300,
                    draggable:true,
                    slidesToShow: 4,
                    useCSS:true,
                    slidesToScroll: 4,

                    responsive: [{

                        breakpoint: 1024,
                        settings: {
                            slidesToShow: 4,
                        }

                    }, {

                        breakpoint: 600,
                        settings: {
                            slidesToShow: 3,
                            slidesToScroll: 1,
                        }

                    }]
                });

                $(".slick-prev").html("&#8249;");
                $(".slick-next").html("&#8250;");
            });
        });
    </script>

</div>
